
package frc.robot.choreo;

import edu.wpi.first.math.geometry.Pose2d;
import edu.wpi.first.math.geometry.Rotation2d;
import java.util.Map;
import java.util.OptionalInt;

// If these imports cause errors because you're not using ChoreoLib,
// turn off "Include ChoreoLib-specific Helpers" in Choreo's codegen settings.
import choreo.auto.AutoRoutine;
import choreo.auto.AutoTrajectory;

/**
 * A class containing the name, start pose, end pose, and total time of every Choreo trajectory.
 * This prevents your code from referencing deleted or misspelled trajectories,
 * and removes the need for JSON parsing to load a trajectory's essential data.
 * DO NOT MODIFY THIS FILE YOURSELF! It is automatically generated by Choreo.
 */
public record ChoreoTraj(
    String name,
    OptionalInt segment,
    double totalTimeSecs,
    Pose2d initialPoseBlue,
    Pose2d endPoseBlue
) {
    public static final ChoreoTraj DepotAuto = new ChoreoTraj(
	    "DepotAuto",
	    OptionalInt.empty(),
	    4.25588,
	    new Pose2d(3.672, 6.862, Rotation2d.fromRadians(1.571)),
	    new Pose2d(0.359, 6.784, Rotation2d.fromRadians(1.546))
	);
	public static final ChoreoTraj MiddletoHP = new ChoreoTraj(
	    "MiddletoHP",
	    OptionalInt.empty(),
	    2.50126,
	    new Pose2d(3.747, 2.925, Rotation2d.fromRadians(3.142)),
	    new Pose2d(0.347, 0.7, Rotation2d.fromRadians(3.142))
	);
	public static final ChoreoTraj OutpostAuto_1 = new ChoreoTraj(
	    "OutpostAuto_1",
	    OptionalInt.empty(),
	    2.2656,
	    new Pose2d(3.936, 0.655, Rotation2d.fromRadians(0)),
	    new Pose2d(0.347, 0.7, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj OutpostAuto_2 = new ChoreoTraj(
	    "OutpostAuto_2",
	    OptionalInt.empty(),
	    3.68347,
	    new Pose2d(4.188, 0.547, Rotation2d.fromRadians(0)),
	    new Pose2d(7.762, 3.503, Rotation2d.fromRadians(1.388))
	);
	public static final ChoreoTraj TestPath = new ChoreoTraj(
	    "TestPath",
	    OptionalInt.empty(),
	    6.79288,
	    new Pose2d(2.404, 6.412, Rotation2d.fromRadians(0)),
	    new Pose2d(2.404, 6.412, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj TestPath$0 = new ChoreoTraj(
	    "TestPath",
	    OptionalInt.of(0),
	    2.46725,
	    new Pose2d(2.404, 6.412, Rotation2d.fromRadians(0)),
	    new Pose2d(2.042, 4.02, Rotation2d.fromRadians(2.729))
	);
	public static final ChoreoTraj TestPath$1 = new ChoreoTraj(
	    "TestPath",
	    OptionalInt.of(1),
	    1.7489600000000003,
	    new Pose2d(2.042, 4.02, Rotation2d.fromRadians(2.729)),
	    new Pose2d(3.376, 4.224, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj TestPath$2 = new ChoreoTraj(
	    "TestPath",
	    OptionalInt.of(2),
	    2.57667,
	    new Pose2d(3.376, 4.224, Rotation2d.fromRadians(0)),
	    new Pose2d(2.404, 6.412, Rotation2d.fromRadians(0))
	);
	public static final ChoreoTraj TrenchAuto = new ChoreoTraj(
	    "TrenchAuto",
	    OptionalInt.empty(),
	    11.25662,
	    new Pose2d(3.582, 7.314, Rotation2d.fromRadians(1.572)),
	    new Pose2d(2.67, 7.05, Rotation2d.fromRadians(1.727))
	);
	public static final ChoreoTraj YOINKYPLOINKY = new ChoreoTraj(
	    "YOINKYPLOINKY",
	    OptionalInt.empty(),
	    7.83249,
	    new Pose2d(4.276, 7.429, Rotation2d.fromRadians(0)),
	    new Pose2d(3.67, 7.41, Rotation2d.fromRadians(3.142))
	);
	public static final ChoreoTraj NewPath_copy1 = new ChoreoTraj(
	    "NewPath_copy1",
	    OptionalInt.empty(),
	    3.25184,
	    new Pose2d(4.288, 7.447, Rotation2d.fromRadians(0)),
	    new Pose2d(3.623, 7.458, Rotation2d.fromRadians(0))
	);

    /**
     * A map between trajectory names and their corresponding data.
     * This allows for trajectory data to be looked up with strings during runtime.
     */
    public static final Map<String, ChoreoTraj> ALL_TRAJECTORIES = Map.ofEntries(
    	Map.entry("DepotAuto", DepotAuto),
		Map.entry("MiddletoHP", MiddletoHP),
		Map.entry("OutpostAuto_1", OutpostAuto_1),
		Map.entry("OutpostAuto_2", OutpostAuto_2),
		Map.entry("TestPath", TestPath),
		Map.entry("TestPath$0", TestPath$0),
		Map.entry("TestPath$1", TestPath$1),
		Map.entry("TestPath$2", TestPath$2),
		Map.entry("TrenchAuto", TrenchAuto),
		Map.entry("YOINKYPLOINKY", YOINKYPLOINKY),
		Map.entry("NewPath_copy1", NewPath_copy1)
    );

    /**
     * Looks up the ChoreoTraj segment of the given overall ChoreoTraj.
     * WARNING: will raise an exception if not called with a valid segment index.
     */
    public ChoreoTraj segment(int segment) {
        var traj = ChoreoTraj.ALL_TRAJECTORIES.get(this.name + "$" + segment);
        if (traj == null) {
            throw new NullPointerException("Trajectory " + this.name + " does not have segment #" + segment + ".");
        }
        return traj;
    }
    
    // If these methods cause errors because you're not using ChoreoLib,
    // turn off "Include ChoreoLib-specific Helpers" in Choreo's codegen settings.
    /**
     * Load an AutoTrajectory directly from a ChoreoTraj, which may be a segment of a larger trajectory.
     */
    public AutoTrajectory asAutoTraj(AutoRoutine routine) {
        if (this.segment.isPresent()) {
            return routine.trajectory(this.name, this.segment.getAsInt());
        }
        return routine.trajectory(this.name);
    }
}
